version: '3.7'

services:
  tanks_nginx_reverse_proxy:
    platform: linux/amd64
    build:
      context: ../docker/tanks-nginx-reverse-proxy
    ports:
      - "9443:443"
    depends_on:
      - tanks_mirror_game_server
      - tanks_web_game_client

  tanks_apache_reverse_proxy:
    build:
      context: ../docker/tanks-apache-reverse-proxy
    ports:
      - "10443:443"
    depends_on:
      - tanks_mirror_game_server
      - tanks_web_game_client

  tanks_web_game_client:
    platform: linux/amd64
    build:
      context: ../docker/tanks-web-client
    ports:
      - "9080:80"

  tanks_mirror_game_server:
    platform: linux/amd64
    build:
      context: ../docker/tanks-game-server
    ports:
      - "9777:7777/udp"
      - "9778:7778/tcp"
